### ISSUE TITLE
Image/Audio challenge rendering in Background

### ISSUE THREAD

**Issue by MovGP0** [google/recaptcha#169]
I have the isse that the captcha is rendering fine, except when it thinks that I am a bot and the Image/Audio  chellenge appears. Setting the z-index manually does not help. 

```css
recaptcha-script + div {
    margin-left: auto;
    margin-right: auto;
    z-index: 1000000;
}
```

Any ideas? 

![recaptcha bug](https://user-images.githubusercontent.com/83339/28260846-268f16da-6add-11e7-9538-0828f1026266.png)
